# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
Recipe.delete_all

# Deserts
Recipe.create(instructions: "Peaches!!", favorite: true, name: 'Fresh Peach Cobbler I', difficulty: 1, remote_photo_url: 'http://4.bp.blogspot.com/-qEDAjrCdmJk/TjrFmh_rMOI/AAAAAAAAA0g/ydwQKoXaD7c/s1600/Peach+Cobbler.jpg', description: 'Best dessert in planet earth!')
Recipe.create(instructions: "Enjoy!", favorite: true, name: 'New York Cheesecake', difficulty: 2, remote_photo_url: 'http://thepurplespoon.files.wordpress.com/2011/03/img_0780.jpg', description: 'This cake is easy to make, and it is so delicious. Everyone that is tried it has said it tasted just like the ones in a deli! You will love it!')
Recipe.create(instructions: "Mmmmmm Chocolate", favorite: false, name: 'Chocolate Chip Cookies', difficulty: 2, remote_photo_url: 'http://upload.wikimedia.org/wikipedia/commons/b/b9/Chocolate_Chip_Cookies_-_kimberlykv.jpg', description: 'Everybody wants this recipe when I take them in for a carry-in. To make them award winning, my daughter, Tegan, made them for a cookie baking contest and won a red ribbon! You can use any flavor pudding you like for this recipe.')
Recipe.create(instructions: "", favorite: false, name: 'Blueberry Cobbler', difficulty: 3, remote_photo_url: 'http://static.tastykitchen.com/recipes/files/2010/06/BlueberryCobbler.jpg', description: 'I have tinkered and tinkered, and this is the very best blueberry cobbler recipe I have found.')
Recipe.create(instructions: "", favorite: false, name: 'Tiramisu', difficulty: 2, remote_photo_url: 'http://chocolatechillimango.com/wp-content/uploads/2011/06/tiramisu_0646_wm.jpg', description: 'Mascarpone custard layered with whipped cream and rum and coffee soaked ladyfingers.')
Recipe.create(instructions: "Remember apples...", favorite: false, name: 'Apple Pie', difficulty: 1, remote_photo_url: 'http://thesouthernvegan.files.wordpress.com/2012/02/apple-pie.jpg', description: 'This is THE American Apple Pie.')
Recipe.create(instructions: "", favorite: false, name: 'Peach Cobbler', difficulty: 1, remote_photo_url: 'http://www.twotwentyone.net/wp-content/uploads/blogger/-gz4svV6Yv0o/TkSwnmwl_oI/AAAAAAAABag/vfHdrJeewTw/s1600/peach%2Bcobbler%2B4.jpg', description: '"I have been experimenting with cobbler for some time and this recipe is the final result. Loved by all. Use fresh Georgia peaches, of course!')
Recipe.create(instructions: "eeeee", favorite: true, name: 'Strawberries and Cream Cake', difficulty: 1, remote_photo_url: 'http://farm8.staticflickr.com/7122/6981134930_7e06e69bb1_b.jpg', description: 'Makes an elegant presentation without too much fuss.')
Recipe.create(instructions: "", favorite: false, name: 'Black Magic Cake', difficulty: 1, remote_photo_url: 'http://4.bp.blogspot.com/-9ef3eIZXOPs/TpXT6yJvayI/AAAAAAAAAI0/4YcH7Fx5tXo/s640/IMG_4200.JPG', description: 'A simple dessert that is great served with ice cream.')
Recipe.create(instructions: "", favorite: false, name: 'Apple Crisp II', difficulty: 1, remote_photo_url: 'http://3.bp.blogspot.com/_UIXOn06Pz70/SRJfH3RjoDI/AAAAAAAAFRQ/DCihBHoAVfc/s800/Vanilla+Apple+Crisp+with+Caramel+Sauce+500.jpg', description: 'Sweet as heaven.')
Recipe.create(instructions: "The best!", favorite: true, name: 'Best Brownies', difficulty: 1, remote_photo_url: 'https://lh4.googleusercontent.com/-_qwK436y_Lw/TXovTJ79SdI/AAAAAAAAEXk/Xc8nXXWyg60/s1600/Sweet+and+Salty+Brownie.JPG', description: 'These brownies always turn out!')
Recipe.create(instructions: "Carrots make this cake healthy!", favorite: false, name: 'Carrot Cake', difficulty: 1, remote_photo_url: 'http://www.cookingclassy.com/wp-content/uploads/2012/11/carrot+cake+4.jpg', description: 'My Grandfather (Sam) was famous for this cake. Everyone who knew him, knows of his famous carrot cake.')
Recipe.create(instructions: "Juicy and crispy...", favorite: false, name: 'Juicy Peach Crisp', difficulty: 1, remote_photo_url: 'http://www.the-baker-chick.com/wp-content/uploads/2013/07/peach.jpg', description: 'This recipe takes the simplicity of fresh peaches and turns them into a scrumptious dessert!')
Recipe.create(instructions: "Tripple!", favorite: false, name: 'Triple Berry Sorbet', difficulty: 1, remote_photo_url: 'http://comfybelly.com/wp-content/uploads/2009/05/Strawberry-Sorbet.jpg', description: 'This tart, refreshing sorbet makes a great light dessert!')
Recipe.create(instructions: "", favorite: false, name: 'Country Apple Dumplings', difficulty: 1, remote_photo_url: 'http://recipecrave.com/wp-content/uploads/Country_apple_dumplings-1500x1125.jpg', description: 'Oh my Goodness!! Who knew that fresh apples, crescent roll dough, and citrus soda could make such a wonderful treat!')